Add wkhtmltopdf custom URL support to handle scenarios where the Debian version in the Python Docker image differs from Debian Bookworm

diff --git a/dockerfile.example b/dockerfile.example
--- a/dockerfile.example
+++ b/dockerfile.example
@@ -7,14 +7,24 @@ ARG APT_ADDITIONAL_PACKAGES
 ARG INSTALL_LIBREOFFICE
 ARG POSTGRESQL_VERSION
 ARG VSCODE_DIRECT_DOWNLOAD_URL
+ARG WKHTMLTOPDF_DIRECT_DOWNLOAD_URL
 
 # install odoo dependencies
 RUN apt update; \
     apt install -y wget software-properties-common build-essential libxslt-dev libzip-dev libldap2-dev libsasl2-dev node-less libpq-dev tmux xfonts-75dpi fontconfig libxrender1 xfonts-base libcups2-dev
 
-RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb; \
-    dpkg -i ./wkhtmltox_0.12.6.1-3.bookworm_amd64.deb; \
-    rm ./wkhtmltox_0.12.6.1-3.bookworm_amd64.deb
+RUN if [ -n "$WKHTMLTOPDF_DIRECT_DOWNLOAD_URL" ] && { [ "$WKHTMLTOPDF_DIRECT_DOWNLOAD_URL" != "${WKHTMLTOPDF_DIRECT_DOWNLOAD_URL#[http://]}" ] || [ "$WKHTMLTOPDF_DIRECT_DOWNLOAD_URL" != "${WKHTMLTOPDF_DIRECT_DOWNLOAD_URL#[https://]}" ]; }; then \
+        filename="wkhtmltox_installer.deb"; \
+        wget -O "$filename" $WKHTMLTOPDF_DIRECT_DOWNLOAD_URL; \
+        if [ $? -ne 0 ]; then \
+            echo "Error downloading wkhtmltopdf. Exiting." >&2; \
+            exit 1; \
+        fi; \
+        apt install -y "./$filename"; \
+        rm "$filename"; \
+    else \
+        echo "No direct download URL provided for wkhtmltopdf. Skipping installation." >&2; \
+    fi
 
 RUN apt install -y cabextract; \
     wget http://ftp.jp.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8.1_all.deb; \
